### PR TITLE
Dan stop survey

### LINKED ISSUE #22: Stop survey from the server
For this issue, please create a branch directly from "AdaptsBranchV3"

### PR DESCRIPTION
**Pull request by dan-chop-ris**
Fixes #22

### CODE REVIEW

**Comment by mashfiqui-rabbi** [comment]
Dan, I have a comment. please check.

**Comment by dan-chop-ris** [comment]
Hi Mash - 
I made that update.  Can you merge my pull request ?

**Comment by mashfiqui-rabbi** [comment]
Dan, I have to carefully review this request since I moved the logic of the survey start and end to "home.page.ts."

**Comment by mashfiqui-rabbi** [comment]
Thanks, Dan, for helping us with this. I merged the code. I used an icon instead of text because the iOS app title is in the middle and the survey paused text is too long.

**Comment by mashfiqui-rabbi** [comment]
Thanks, Dan, for helping us with this. I merged the code. I used an icon instead of text because the iOS app title is in the middle and the survey paused text is too long.

**Comment by mashfiqui-rabbi** [comment]
Thanks, Dan, for helping us with this. I merged the code. I used an icon instead of text because the iOS app title is in the middle and the survey paused text is too long.

**Pull request merged**
