### PR TITLE
Liying chop s3

### PR DESCRIPTION
**Pull request by lxh37**
Files updated for S3.

### CODE REVIEW

**Comment by mashfiqui-rabbi** [comment]
Liying, I just did the code review. It looks like you made a lot of changes. Did you write in the commit messages everything you changed?

**Comment by lxh37** [comment]
Some changes are necessary for the code to compile
due to update of packages necessary for S3 to work.
Also I did updates (fix bugs, add comments etc) over
the time and they are in the files related to S3, so I
update those files to latest version.

Main things are:
0. update package (package.json)
1.  update storage module
2.  update dynamic survey component to add username column and have json file to have a consistent format.
3. alert dialog to have survey done between 6pm - midnight.
4. life-insight fix, the local storage to hold the information will only hold 7 day information. (to avoid growing infinitely large), it is done in dynamic survey component too.

Best,
Liying


________________________________

**Comment by mashfiqui-rabbi** [comment]
Liying, create a new commit message and put the exact stuff you wrote above.

**Comment by mashfiqui-rabbi** [comment]
Liying, can you request a pull request with AdaptsBranchBV3. It has some of your old codes that I am not able to merge.

**Pull request closed without merging**
